apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: workshop
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:9.5.3
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: POSTGRES_USER
          value: workshop
        - name: POSTGRES_DB
          value: workshop_development
        ports:
        - containerPort: 5432
          name: postgres
