# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f3b282872849bb4afdc732fd5fcfdbdda2a2a00b89ff657827d426ffe0fd97a5a64244c19815be64f09346b7e6e657caa221c3a0022f6b9eedb84592bd4bac

test:
  secret_key_base: daa3971e64c36028d34d183e61f8d95367790b1f4bfbb1d5ffcec1e26516d2b308ab79e8e25e995861c4eed069d41fa262d2184e40c912a2f1597d829c89ffe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
