apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: pacuna/workshop:1.0.2
        command: ["/bin/bash", "./setup.sh"]
      restartPolicy: Never
